### PR TITLE
Add missing strings

### PR DESCRIPTION
**Pull request by Eng2Heb**

### CODE REVIEW

**Comment by YggdrasiI** [comment]
Hello, I had two questions about the pull request:

1. Backslashes are now escaped. Is this really correct?
I.e.
```
< msgstr "הצג חיזוי \"מנגן כעת\" כרקע"
---
> msgstr "הצג חיזוי \\\"מנגן כעת \\\" כרקע"
```

2. Is your translation related to the translation of the [https://github.com/xbmc/skin.confluence](official repository)?
If no, I would suggest you push your request in their repository.
If yes, I could also wait if your translation update was pushed into their repository.


Regards YggdrasiI

**Comment by Eng2Heb** [comment]
Hi, 
1. without backslush kodi will produce an error in the log on some chars like ", ' and so on in Hebrew. 
The 3 chars \\\ are the way the Github WYSIWUG editor interpret the backslush.

2.  It is related but not the same. I need to update in transfix and in a month or so it will be loaded into the git.

**Comment by YggdrasiI** [comment]
Ok, I will add your translation tomorrow, but still assume that "\\\  will show an undesired backlash in the Kodi interface. 
(I've tested it with an old Kodi 15.2 instance, but as Non-Hebrew user I'm not totally sure. :))

**Comment by Eng2Heb** [comment]
I made a change in the code with the backslash but the issue must be reported to github because it's a bug.

**Comment by YggdrasiI** [comment]
The pull request was merged into the master branch, but got new commit id's due a 'git rebase'
(Latest commit id is 7bdc13f629ba60b29d0abd7f4c0bd49aeb09423d)

Thanks for the contributing.

**Pull request closed without merging**
